function imagesHaars = extractHaars(imagesData)
    samples = size(imagesData,3);
    imagesHaars = zeros(samples,4);
    for i = 1:samples
        imagesHaars(i,1) = haar(imagesData(:,:,i),haarMatrices(1));
        imagesHaars(i,2) = haar(imagesData(:,:,i),haarMatrices(2));
        imagesHaars(i,3) = haar(imagesData(:,:,i),haarMatrices(3));
        imagesHaars(i,4) = haar(imagesData(:,:,i),haarMatrices(4));
    end
end


function imageHaar = haar(imageData,haarMatrix)
    imageHaar = 0;
    for i = 1:6
        for j = 1:6
            imageHaar = imageHaar + imageData(i,j)*haarMatrix(i,j);
        end
    end
end


function haarMatrix = haarMatrices(index)
    if index == 1
        haarMatrix = [ ...
            [1 1 1 1 1 1];...
            [1 1 1 1 1 1];...
            [1 1 1 1 1 1];...
            [-1 -1 -1 -1 -1 -1];...
            [-1 -1 -1 -1 -1 -1];...
            [-1 -1 -1 -1 -1 -1];...
            ];
    elseif index == 2
        haarMatrix = [ ...
            [-1 -1 -1 1 1 1];...
            [-1 -1 -1 1 1 1];...
            [-1 -1 -1 1 1 1];...
            [-1 -1 -1 1 1 1];...
            [-1 -1 -1 1 1 1];...
            [-1 -1 -1 1 1 1];...
            ];
    elseif index == 3
        haarMatrix = [ ...
            [1 1 -1 -1 1 1];...
            [1 1 -1 -1 1 1];...
            [1 1 -1 -1 1 1];...
            [1 1 -1 -1 1 1];...
            [1 1 -1 -1 1 1];...
            [1 1 -1 -1 1 1];...
            ];
    elseif index == 4
        haarMatrix = [ ...
            [-1 -1 -1 1 1 1];...
            [-1 -1 -1 1 1 1];...
            [-1 -1 -1 1 1 1];...
            [1 1 1 -1 -1 -1];...
            [1 1 1 -1 -1 -1];...
            [1 1 1 -1 -1 -1];...
            ];
    end
end
